site_name: Paintomics v3.0 Documentation
pages:
- ['index.md', 'Home']
- ['0_install.md', 'Install', 'Installing PaintOmics 3']
- ['1_kegg.md', 'Getting start', 'The KEGG Pathways database']
- ['2_1_accepted_input.md', 'Getting start', 'Accepted input data']
- ['2_2_cloud_drive.md', 'Getting start', 'Cloud Drive']
- ['4_1_pathway_enrichment.md', 'Getting start', 'Pathway Enrichment Analysis (PEA)']
- ['4_2_kegg_categories.md', 'Getting start', 'Hierarchical classifications for pathways']
- ['4_3_pathways_network.md', 'Getting start', 'The pathways interaction network']
- ['5_1_browsing_pathways.md', 'Getting start', 'Multi-omic pathway-based visualisation']
- ['7_license.md', 'About', 'License']
theme: readthedocs
